config/routes.rb
Rails.application.routes.draw do
  resources :data
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/datum.rb
class Datum < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  before_action :set_datum, only: %i[ show edit update destroy ]

  # GET /data or /data.json
  def index
    @data = Datum.all
    @version = ActiveRecord::Base.connection.execute("SELECT version();").first
  end

  # GET /data/1 or /data/1.json
  def show
  end

  # GET /data/new
  def new
    @datum = Datum.new
  end

  # GET /data/1/edit
  def edit
  end

  # POST /data or /data.json
  def create
    @datum = Datum.new(datum_params)

    respond_to do |format|
      if @datum.save
        format.html { redirect_to datum_url(@datum), notice: "Datum was successfully created." }
        format.json { render :show, status: :created, location: @datum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data/1 or /data/1.json
  def update
    respond_to do |format|
      if @datum.update(datum_params)
        format.html { redirect_to datum_url(@datum), notice: "Datum was successfully updated." }
        format.json { render :show, status: :ok, location: @datum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1 or /data/1.json
  def destroy
    @datum.destroy!

    respond_to do |format|
      format.html { redirect_to data_url, notice: "Datum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datum
      @datum = Datum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def datum_params
      params.require(:datum).permit(:someData)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    # GET /
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/data/_datum.html.erb
<div id="<%= dom_id datum %>">
  <p>
    <strong>Somedata:</strong>
    <%= datum.someData %>
  </p>

</div>

app/views/data/_form.html.erb
<%= form_with(model: datum) do |form| %>
  <% if datum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
        <% datum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :someData, style: "display: block" %>
    <%= form.text_field :someData %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/data/edit.html.erb
<h1>Editing datum</h1>

<%= render "form", datum: @datum %>

<br>

<div>
  <%= link_to "Show this datum", @datum %> |
  <%= link_to "Back to data", data_path %>
</div>

app/views/data/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Data</h1>

<div id="data">
  <% @data.each do |datum| %>
    <%= render datum %>
    <p>
      <%= link_to "Show this datum", datum %>
    </p>
  <% end %>
</div>

<%= link_to "New datum", new_datum_path %>

<div><%= @version %></div>

app/views/data/new.html.erb
<h1>New datum</h1>

<%= render "form", datum: @datum %>

<br>

<div>
  <%= link_to "Back to data", data_path %>
</div>

app/views/data/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @datum %>

<div>
  <%= link_to "Edit this datum", edit_datum_path(@datum) %> |
  <%= link_to "Back to data", data_path %>

  <%= button_to "Destroy this datum", @datum, method: :delete %>
</div>

app/views/home/index.html.erb
<%= image_tag "kubernetes.png", height: 150 %>
<h1>
  Practical task on the Kubernetes topic
</h1>
<h2>
  Some data:
</h2>

<p>{name: Tobi, age: 2, species: unknown}</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>